version: '3.8'

services:
  frontend-production:
    image: ghcr.io/kkristianr/semantic-shift-frontend:production
    container_name: semantic-shift-frontend-production
    restart: unless-stopped
    networks:
      - semantic-shift-production

  backend-production:
    image: ghcr.io/kkristianr/semantic-shift-backend:production
    container_name: semantic-shift-backend-production
    restart: unless-stopped
    environment:
      - DEBUG=false
      - DATABASE_URL=sqlite:///tmp/app.db
      - BACKEND_CORS_ORIGINS=https://sem.kristiam.xyz
    volumes:
      # Temporary storage for SQLite - will be cleaned up after sessions
      - /tmp/semantic-shift-production:/tmp
    networks:
      - semantic-shift-production
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  semantic-shift-production:
    name: semantic-shift-production
    driver: bridge
